// <auto-generated />
namespace BaseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addAliasCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAliasCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202305271924389_addAliasCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
