// <auto-generated />
namespace BaseProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addImagesinCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addImagesinCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202306011753514_addImagesinCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
